"""Utilities for working with source URLs and article citations.

This module provides helpers to extract a domain from a URL and to
filter/renumber citations in an article so that only cited sources are
kept and citation numbers are sequential.
"""

from urllib.parse import urlparse
import logging
import re

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def extract_domain(url: str) -> str:
    """Extract the canonical domain (without ``www.``) from a URL string.

    :param url: The URL to parse.
    :returns: Domain string without leading ``www.`` or an empty string on error.
    """
    try:
        parsed = urlparse(url)
        domain = parsed.netloc
        # Remove 'www.' prefix if present
        if domain.startswith('www.'):
            domain = domain[4:]
        return domain
    except Exception:
        return ""
    
def filter_and_renumber_sources(article_text: str, sources: list, sources_provided_count: int) -> tuple:
    """Filter provided sources to only those cited in ``article_text`` and
    renumber citation indices to be sequential.

    :param article_text: Article content containing citation markers like ``[1]``.
    :param sources: List of source dicts in the original order provided.
    :param sources_provided_count: Count of sources originally provided (for stats).
    :returns: Tuple of ``(renumbered_text, filtered_sources, stats_dict)``.
    """
    # Extract all citation numbers from article
    citations = re.findall(r'\[(\d+)\]', article_text)
    
    # Convert to integers and get unique citation numbers (sorted)
    cited_numbers = sorted(set(int(c) for c in citations))
    
    if not cited_numbers:
        # No citations found, return as-is
        return article_text, sources, {
            "total_sources_provided": sources_provided_count,
            "total_sources_returned": len(sources),
            "sources_cited": 0,
            "sources_filtered": 0,
            "sources_removed": len(sources),
            "cited_numbers_original": [],
            "citation_mapping": {},
            "unused_numbers": list(range(1, len(sources) + 1)),
            "extra_sources_added": False,
            "extra_sources_count": 0,
            "removal_percentage": 100.0
        }
    
    # Create mapping: old citation number -> new citation number
    # Example: {1: 1, 2: 2, 5: 3, 7: 4}
    citation_mapping = {old_num: new_num for new_num, old_num in enumerate(cited_numbers, start=1)}
    
    # Filter sources to only include cited ones (in citation order)
    filtered_sources = []
    for cite_num in cited_numbers:
        array_index = cite_num - 1  # Convert to 0-based
        if 0 <= array_index < len(sources):
            filtered_sources.append(sources[array_index])
        else:
            logger.warning(f"Citation [{cite_num}] found but source not in list (have {len(sources)} sources)")
    
    renumbered_text = article_text
    
    # Step 1: Replace all citations with unique placeholders
    # Example: [2] -> __CITE_2__, [3] -> __CITE_3__, etc.
    for old_num in citation_mapping.keys():
        pattern = r'\[' + str(old_num) + r'\]'
        placeholder = f'__CITE_{old_num}__'
        renumbered_text = re.sub(pattern, placeholder, renumbered_text)
    
    # Step 2: Replace placeholders with new citation numbers
    # Example: __CITE_2__ -> [1], __CITE_3__ -> [2], etc.
    for old_num, new_num in citation_mapping.items():
        placeholder = f'__CITE_{old_num}__'
        replacement = f'[{new_num}]'
        renumbered_text = renumbered_text.replace(placeholder, replacement)
    
    # Calculate statistics
    extra_sources_added = len(sources) > sources_provided_count
    
    stats = {
        "total_sources_provided": sources_provided_count,
        "total_sources_returned": len(sources),
        "sources_cited": len(cited_numbers),
        "sources_filtered": len(filtered_sources),
        "sources_removed": len(sources) - len(cited_numbers),
        "cited_numbers_original": cited_numbers,
        "citation_mapping": citation_mapping,
        "unused_numbers": [i for i in range(1, len(sources) + 1) if i not in cited_numbers],
        "extra_sources_added": extra_sources_added,
        "extra_sources_count": len(sources) - sources_provided_count if extra_sources_added else 0,
        "removal_percentage": round((len(sources) - len(cited_numbers)) / len(sources) * 100, 1) if sources else 0
    }
    
    return renumbered_text, filtered_sources, stats

CREDIBLE_SOURCES = {
 "abcnews.go.com",
    "academic.oup.com",
    "accenture.com",
    "afp.com",
    "ai.meta.com",
    "ama-assn.org",
    "anthropic.com",
    "ap.org",
    "arxiv.org",
    "aws.amazon.com",
    "azure.microsoft.com",
    "bain.com",
    "bcg.com",
    "blog.google",
    "bls.gov",
    "brookings.edu",
    "brown.edu",
    "businessinsider.com",
    "cambridge.org",
    "cbsnews.com",
    "cfr.org",
    "cms.gov",
    "cmu.edu",
    "congress.gov",
    "csis.org",
    "deloitte.com",
    "developer.nvidia.com",
    "discovermagazine.com",
    "ec.europa.eu",
    "ecb.europa.eu",
    "ed.gov",
    "energy.gov",
    "europarl.europa.eu",
    "ey.com",
    "fda.gov",
    "fortune.com",
    "frontiersin.org",
    "gatech.edu",
    "harvard.edu",
    "hbr.org",
    "ibm.com",
    "iclr.cc",
    "icml.cc",
    "imf.org",
    "jamanetwork.com",
    "kpmg.com",
    "livescience.com",
    "mckinsey.com",
    "microsoft.com",
    "morningstar.com",
    "nature.com",
    "neurips.cc",
    "nih.gov",
    "nsf.gov",
    "nvidia.com",
    "oecd.org",
    "onlinelibrary.wiley.com",
    "openai.com",
    "ox.ac.uk",
    "pewresearch.org",
    "physicsworld.com",
    "pnas.org",
    "politico.com",
    "princeton.edu",
    "pwc.com",
    "research.google",
    "science.org",
    "sciencedaily.com",
    "scmp.com",
    "sloanreview.mit.edu",
    "smithsonianmag.com",
    "sydney.edu.au",
    "tandfonline.com",
    "techcrunch.com",
    "time.com",
    "ucl.ac.uk",
    "un.org",
    "unc.edu",
    "unesco.org",
    "unsw.edu.au",
    "whitehouse.gov",
    "who.int",
    "academy.openai.com",
    "acceleratelearning.stanford.edu",
    "agupubs.onlinelibrary.wiley.com",
    "ai.seas.upenn.edu",
    "aifarms.illinois.edu",
    "alz-journals.onlinelibrary.wiley.com",
    "apps.apple.com",
    "arpa-e-foa.energy.gov",
    "ascode.osu.edu",
    "assets.anthropic.com",
    "assets.kpmg.com",
    "atkinson.cornell.edu",
    "besjournals.onlinelibrary.wiley.com",
    "blog.peabody.vanderbilt.edu",
    "blog.seas.upenn.edu",
    "blogs.microsoft.com",
    "blogs.nvidia.com",
    "bsppjournals.onlinelibrary.wiley.com",
    "budgetlab.yale.edu",
    "budgetmodel.wharton.upenn.edu",
    "businessdevelopment.mayoclinic.org",
    "cacm.acm.org",
    "careerservices.fas.harvard.edu",
    "casmi.northwestern.edu",
    "cdn-dynmedia-1.microsoft.com",
    "cedefop.europa.eu",
    "cee.illinois.edu",
    "cisr.mit.edu",
    "cleanenergyforum.yale.edu",
    "climate.uchicago.edu",
    "climatecollab.uci.edu",
    "cmr.berkeley.edu",
    "cns.utexas.edu",
    "commission.europa.eu",
    "community.ibm.com",
    "community.openai.com",
    "corpgov.law.harvard.edu",
    "cset.georgetown.edu",
    "ctl.ox.ac.uk",
    "ctl.utexas.edu",
    "data.consilium.europa.eu",
    "datasmart.hks.harvard.edu",
    "dbmi.hms.harvard.edu",
    "developer.ibm.com",
    "digital-strategy.ec.europa.eu",
    "dl.acm.org",
    "e360.yale.edu",
    "edhub.ama-assn.org",
    "edps.europa.eu",
    "education.ec.europa.eu",
    "education.illinois.edu",
    "edunewsletter.openai.com",
    "eere-exchange.energy.gov",
    "eit.europa.eu",
    "energy.cmu.edu",
    "energy.ec.europa.eu",
    "energy.mit.edu",
    "energy.utexas.edu",
    "energypolicy.columbia.edu",
    "environment.ec.europa.eu",
    "ep.jhu.edu",
    "epic.noaa.gov",
    "eric.ed.gov",
    "esajournals.onlinelibrary.wiley.com",
    "esto.nasa.gov",
    "ethics.harvard.edu",
    "european-research-area.ec.europa.eu",
    "execed.business.columbia.edu",
    "executive.mit.edu",
    "executiveeducation.wharton.upenn.edu",
    "fic.tufts.edu",
    "files.eric.ed.gov",
    "fuqua.duke.edu",
    "gsb.stanford.edu",
    "gse.harvard.edu",
    "guides.library.georgetown.edu",
    "hai.stanford.edu",
    "hbsp.harvard.edu",
    "health.ec.europa.eu",
    "health.ucdavis.edu",
    "help.openai.com",
    "hms.harvard.edu",
    "hub.jhu.edu",
    "huit.harvard.edu",
    "humanresources.illinois.edu",
    "ieai.sot.tum.de",
    "iee.psu.edu",
    "ietresearch.onlinelibrary.wiley.com",
    "investor.nvidia.com",
    "journals.sagepub.com",
    "knight.as.cornell.edu",
    "knowledge.wharton.upenn.edu",
    "lab.vanderbilt.edu",
    "ldlprogram.web.illinois.edu",
    "lile.duke.edu",
    "med.stanford.edu",
    "media-publications.bcg.com",
    "medicine.yale.edu",
    "medschool.duke.edu",
    "mitili.mit.edu",
    "mitsloan.mit.edu",
    "ncbi.nlm.nih.gov",
    "ncsa.illinois.edu",
    "neuroscience.cam.ac.uk",
    "news.climate.columbia.edu",
    "news.cornell.edu",
    "news.emory.edu",
    "news.engin.umich.edu",
    "news.feinberg.northwestern.edu",
    "news.harvard.edu",
    "news.microsoft.com",
    "news.mit.edu",
    "news.osu.edu",
    "news.rice.edu",
    "news.stanford.edu",
    "news.uchicago.edu",
    "news.un.org",
    "news.utexas.edu",
    "newsnetwork.mayoclinic.org",
    "newsroom.accenture.com",
    "newsroom.ibm.com",
    "newsroom.wiley.com",
    "nvidianews.nvidia.com",
    "oaa.osu.edu",
    "oaisc.fas.harvard.edu",
    "online.lifelonglearning.jhu.edu",
    "papers.ssrn.com",
    "partner.microsoft.com",
    "pmc.ncbi.nlm.nih.gov",
    "presidency.ucsb.edu",
    "professional.dce.harvard.edu",
    "provost.columbia.edu",
    "pubmed.ncbi.nlm.nih.gov",
    "queue.acm.org",
    "reflect.ucl.ac.uk",
    "registrar.gse.harvard.edu",
    "research-and-innovation.ec.europa.eu",
    "research.nvidia.com",
    "resources.nvidia.com",
    "reutersinstitute.politics.ox.ac.uk",
    "rmets.onlinelibrary.wiley.com",
    "rossier.usc.edu",
    "safecomputing.umich.edu",
    "salatainstitute.harvard.edu",
    "saopaulo.nd.edu",
    "scale.stanford.edu",
    "schaeffer.usc.edu",
    "sesp.northwestern.edu",
    "setr.stanford.edu",
    "sir.advancedleadership.harvard.edu",
    "sites.psu.edu",
    "social.desa.un.org",
    "solve.mit.edu",
    "stemstarts.utexas.edu",
    "teaching.cornell.edu",
    "teachingcommons.stanford.edu",
    "techcommunity.microsoft.com",
    "techpolicy.sanford.duke.edu",
    "thedocs.worldbank.org",
    "today.ucsd.edu",
    "towcenter.columbia.edu",
    "unesdoc.unesco.org",
    "unlocked.microsoft.com",
    "utsc.utoronto.ca",
    "viterbischool.usc.edu",
    "workflow.ap.org",
    "www-cdn.anthropic.com",
    "ysph.yale.edu",
    "988crisissystemshelp.samhsa.gov",
    "ag.idaho.gov",
    "ag.ny.gov",
    "ai.gov",
    "aiaccelerator.af.mil",
    "ameslab.gov",
    "apcp.assembly.ca.gov",
    "attorneygeneral.gov",
    "cde.ca.gov",
    "commerce.senate.gov",
    "copyright.gov",
    "csrc.nist.gov",
    "dean.house.gov",
    "dla.mil",
    "doi.gov",
    "doiu.doi.gov",
    "education.ohio.gov",
    "eia.gov",
    "energycommerce.house.gov",
    "federalregister.gov",
    "federalreserve.gov",
    "gov.ca.gov",
    "hawley.senate.gov",
    "ic3.gov",
    "illinoisattorneygeneral.gov",
    "le.utah.gov",
    "michigan.gov",
    "ncdoj.gov",
    "ncua.gov",
    "newscenter.lbl.gov",
    "nist.gov",
    "njoag.gov",
    "nrel.gov",
    "nysenate.gov",
    "oag.ca.gov",
    "olcf.ornl.gov",
    "portal.ct.gov",
    "progressives.house.gov",
    "statutes.capitol.texas.gov",
    "transportation.gov",
    "trumpwhitehouse.archives.gov",
    "usccr.gov",
    "usda.gov",
    "ussc.gov",
    "ustr.gov",
    "aacsb.edu",
    "ag.purdue.edu",
    "agrilifetoday.tamu.edu",
    "ai-academy.ncsu.edu",
    "ai.fsu.edu",
    "ai.ufl.edu",
    "ai.wfu.edu",
    "aiforgood.itu.int",
    "ailearning.ai.ufl.edu",
    "alphafold.ebi.ac.uk",
    "apu.apus.edu",
    "assessatcuny.commons.gc.cuny.edu",
    "bertie.ces.ncsu.edu",
    "bhr.stern.nyu.edu",
    "blogs.ifas.ufl.edu",
    "bootcamp.colostate.edu",
    "bootcamp.cpe.vt.edu",
    "bowdoin.edu",
    "buffalo.edu",
    "business.purdue.edu",
    "calstate.edu",
    "careers.kogod.american.edu",
    "castleton.edu",
    "catalogue.uncw.edu",
    "cccco.edu",
    "cehd.gmu.edu",
    "cic.edu",
    "clarksoncollege.edu",
    "colorado.edu",
    "cpp.edu",
    "creativeinquiry.lehigh.edu",
    "cs.purdue.edu",
    "cte.utah.edu",
    "ctl.utahtech.edu",
    "datascienceacademy.ncsu.edu",
    "devry.edu",
    "dewv.edu",
    "doe.mass.edu",
    "dr.lib.iastate.edu",
    "ebnet.ac.uk",
    "ecmwf.int",
    "education.purdue.edu",
    "educause.edu",
    "er.educause.edu",
    "essec.edu",
    "fdc.fullerton.edu",
    "fhu.edu",
    "genai.calstate.edu",
    "gmu.edu",
    "hallcenter.ku.edu",
    "hbs.edu",
    "hcctraining.ac.uk",
    "hepi.ac.uk",
    "home.dartmouth.edu",
    "husson.edu",
    "ie.edu",
    "iica.int",
    "indwes.edu",
    "infoguides.gmu.edu",
    "irving.dartmouth.edu",
    "ischool.syracuse.edu",
    "ithaca.edu",
    "itu.int",
    "kogod.american.edu",
    "learningsciences.smu.edu",
    "lgpress.clemson.edu",
    "libguides.lib.siu.edu",
    "libguides.marian.edu",
    "library.educause.edu",
    "library.hbs.edu",
    "medschool.umaryland.edu",
    "miamioh.edu",
    "moreland.edu",
    "msutoday.msu.edu",
    "nam.edu",
    "nccleantech.ncsu.edu",
    "news.clemson.edu",
    "news.delta.ncsu.edu",
    "news.gsu.edu",
    "news.ku.edu",
    "news.njit.edu",
    "news.northeastern.edu",
    "news.ufl.edu",
    "news.unl.edu",
    "news.vt.edu",
    "nu.edu",
    "online.champlain.edu",
    "online.ysu.edu",
    "onlinedegrees.sandiego.edu",
    "onlineprograms.education.uiowa.edu",
    "ospra.udmercy.edu",
    "park.edu",
    "pce.sandiego.edu",
    "phoenix.edu",
    "policies.northeastern.edu",
    "provost.utsa.edu",
    "purdue.edu",
    "pwcs.edu",
    "research.pitt.edu",
    "responsibleai.arizona.edu",
    "rhsmith.umd.edu",
    "sac.edu",
    "sc.edu",
    "scu.edu",
    "sessions.edu",
    "sites.campbell.edu",
    "sjf.edu",
    "sjsu.edu",
    "sph.umn.edu",
    "stars.library.ucf.edu",
    "teaching.charlotte.edu",
    "teaching.pitt.edu",
    "teaching.uic.edu",
    "tiffin.edu",
    "today.uconn.edu",
    "tpd.tcnj.edu",
    "trac-ai.iastate.edu",
    "ttioc.edu",
    "turing.ac.uk",
    "twin-cities.umn.edu",
    "ucumberlands.edu",
    "udel.edu",
    "ukerc.ac.uk",
    "unfccc.int",
    "unr.edu",
    "uona.edu",
    "upcea.edu",
    "usa.edu",
    "usmd.edu",
    "washington.edu",
    "wcet.wiche.edu",
    "westvalley.edu",
    "windsor.edu",
    "wmo.int",
    "york.ac.uk",
}

# Right now only used to filter out sources that are only user generated content
BLACKLISTED_SOURCES = {
    # Social Media Platforms (user-generated content)
    "twitter.com",
    "x.com",
    "facebook.com",
    "instagram.com",
    "threads.net",
    "tiktok.com",
    "snapchat.com",
    "linkedin.com", 
    "pinterest.com",
    "tumblr.com",
    "mastodon.social",
    "truthsocial.com",
    
    # Video Platforms (user-generated)
    "youtube.com",
    "youtu.be",
    "vimeo.com",
    "dailymotion.com",
    "twitch.tv",
    
    # Forums & Discussion Boards
    "reddit.com",
    "quora.com",
    "stackexchange.com",
    "stackoverflow.com",
    "slack.com",
    
    # Blogging Platforms (user-generated)
    "medium.com",
    "substack.com",
    "blogspot.com",
    "wordpress.com",  
    "wix.com",
    "squarespace.com",
    "ghost.io",
    "blogger.com",
    
    # Content Aggregators (user-submitted)
    "digg.com",
    "slashdot.org",
    "hackernews.com",
    "news.ycombinator.com",

    # Q&A Sites
    "answers.com",
    "answers.yahoo.com",
    "askme.com",
    
    # Other User-Generated Platforms
    "pastebin.com",
    "gist.github.com",
    "notion.so",  #
}
