"""ArticleSector

Revision ID: 755b8b2a2957
Revises: 54fc089e9f0c
Create Date: 2025-12-09 19:48:44.257883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755b8b2a2957'
down_revision: Union[str, Sequence[str], None] = '54fc089e9f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('sector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'sector')
    # ### end Alembic commands ###
