name: Run script every hour

on:
  schedule:
    # Runs every 1 hours
    - cron: "0 */1 * * *"
  workflow_dispatch:  # allows manual runs from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"  # or your required version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend script
        run: |
          python api/test_cron.py
